<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Лифт в будущее</title>
    <meta name="viewport" content="width=1024">

    <!-- Styles -->
    <link rel="stylesheet" href="/css/normalize.css">
    <link rel="stylesheet" href="/css/base.css">
    <link rel="stylesheet" href="/css/grid.css">
    <link rel="stylesheet" href="/css/main.css">
    <link rel="stylesheet" href="/css/helpers.css">
    <link rel="stylesheet" href="/css/pages.css">
    <link rel="stylesheet" href="/css/pickadate.css">

    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Roboto:500&subset=latin,cyrillic" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Roboto+Condensed&subset=latin,cyrillic" rel="stylesheet">
    <script src="//use.typekit.net/uix5mkq.js"></script>
    <script>try{Typekit.load();}catch(e){}</script>
</head>
<body class="page-<?= $controller ?> page-<?= $controller . '-' . $action ?>">
    <?= $this->getContent() ?>

    <!-- Scripts -->
    <script src="/js/jquery.min.js"></script>
    <script src="/js/tinymce/tinymce.min.js"></script>
    <script src="/js/tinymce/jquery.tinymce.min.js"></script>
    <script src="/js/picker.js"></script>
    <script src="/js/picker.date.js"></script>
    <script src="/js/main.js"></script>
</body>
</html>