<? $this->partial('partials/header') ?>

<div class="site-content">
    <div class="site-content-inner">
        <!-- DEBUG -->
        <? if (isset($debug)): ?>
            <pre class="container" style="margin-top: 100px; margin-bottom: 100px; background: #fafafa"><? print_r($debug) ?></pre>
        <? endif ?>
        <!-- /DEBUG -->
    
        <?= $this->getContent() ?>
    </div>
</div>

<? $this->partial('partials/footer') ?>