<div class="container">
    <? if (!empty($result['success'])): ?>

        <div class="alert alert-success">
            <p>Страница удалена</p>
        </div>

    <? elseif (!empty($result['error'])): ?>

        <div class="alert alert-danger">
            <p>Страница не удалена</p>
            
            <? if (!empty($result['error']['hasRights'])): ?>
                <p>Недостаточно прав</p>
            <? endif ?>
        </div>

    <? endif ?>

</div>