<?
extract([
    'classes' => ''
], EXTR_SKIP);
?>

<div class="card <?= $classes ?>">
    <div class="card-header">
        <h2 class="card-title">Прими участие</h2>
        <!-- <span class="card-shrink"></span> -->
    </div>
    <div class="card-body">
        <ol class="activity-list">
            <li>
                <a class="activity-list-figure" href="http://lifttothefuture.ru/intellect2all">
                    <img class="activity-list-image" src="/img/content/thumb-intellect2all.png" width="33" height="33" alt="">
                </a>
                <p class="activity-list-title"><a href="http://lifttothefuture.ru/intellect2all">Конкурс Intellect2All</a></p>
                <p class="activity-list-subcaption activity-list-subcaption-active">Подача заявок открыта!</p>
            </li>
            <li>
                <a class="activity-list-figure" href="/page/show/73">
                    <img class="activity-list-image" src="/img/content/thumb-lift.png" width="33" height="33" alt="">
                </a>
                <p class="activity-list-title"><a href="/page/show/73">Летние школы</a></p>
                <p class="activity-list-subcaption">Летние школы завершены</p>
            </li>
            <li>
                <a class="activity-list-figure" href="http://sp.lifttothefuture.ru">
                    <img class="activity-list-image" src="/img/content/thumb-priority-system.png" width="33" height="33" alt="">
                </a>
                <p class="activity-list-title"><a href="http://sp.lifttothefuture.ru">Конкурс "Система приоритетов"</a></p>
                <p class="activity-list-subcaption">Конкурс завершен, победители объявлены</p>
            </li>
            <li>
                <a class="activity-list-figure" href="http://issf.lifttothefuture.ru/ru/">
                    <img class="activity-list-image" src="/img/content/thumb-school-conference.png" width="33" height="33" alt="">
                </a>
                <p class="activity-list-title"><a href="http://issf.lifttothefuture.ru/ru/">Первая международная конференция школьников</a></p>
                <p class="activity-list-subcaption">Конференция завершила свою работу</p>
            </li>
        </ol>
    </div>
    <!-- <div class="card-footer">
        <a href="#">Все события</a>
    </div> -->
</div>