<?
extract([
    'classes' => ''
], EXTR_SKIP);
?>

<div class="card card-events <?= $classes ?>">
    <div class="card-header">
        <h2 class="card-title">События</h2>
        <!-- <span class="card-shrink"></span> -->
    </div>
    <div class="card-body">
        <ol class="event-list">
            <li>
                <a class="event-list-figure" href="/page/show/76">
                    <img src="/img/content/events-1.jpeg" width="90" height="90" alt="">
                </a>
                <p class="event-list-date">09.08.2014</p>
                <p class="event-list-title"><a href="/page/show/76">Первая научная конференция школьников «Лифт в будущее»!</a></p>
            </li>
            <li>
                <a class="event-list-figure" href="/page/show/77">
                    <img src="/img/content/events-2.jpeg" width="90" height="62" alt="">
                </a>
                <p class="event-list-date">04.08.2014</p>
                <p class="event-list-title"><a href="/page/show/77">Просто о сложном</a></p>
            </li>
            <li>
                <a class="event-list-figure" href="/page/show/78">
                    <img src="/img/content/events-3.png" width="90" height="90" alt="">
                </a>
                <p class="event-list-date">29.07.2014</p>
                <p class="event-list-title"><a href="/page/show/78">Ньюсмейкер по имени «Лифт в будущее»</a></p>
            </li>
        </ol>
    </div>
    <!-- <div class="card-footer">
        <a href="#">Все события</a>
    </div> -->
</div>