<div class="site-footer">
    <div class="site-footer-inner">
        <div class="container">
            <!-- Links -->
            <ul class="site-footer-links">
                <li><a href="http://lifttothefuture.ru/about-lift-to-the-future-program.html">О программе «Лифт в будущее»</a></li>
                <li><a href="http://lifttothefuture.ru/lift-school-all-russia.html">Всероссийская школа</a></li>
                <li><a href="http://lifttothefuture.ru/lift-school-all-russia.html">Межрегиональные школы</a></li>
                <li><a href="http://issf.lifttothefuture.ru/ru/">Международная конференция</a></li>
            </ul>
            <!-- /Links -->
            
            <!-- Info -->
            <div class="site-footer-info">
                <a class="site-footer-logo" href="/">
                    <img src="/img/logo-small.png" width="86" height="58" alt="Лифт в будущее">
                </a>
                <p class="site-footer-contacts">
                    Техподдержка: <a href="mailto:support.sp@lifttothefuture.ru">support.sp@lifttothefuture.ru</a><br>
                    Общие вопросы: <a href="mailto:konkurs.sp@lifttothefuture.ru">konkurs.sp@lifttothefuture.ru</a><br>
                    Телефон: +7 (495) 939-28-80
                </p>
            </div>
            <!-- /Info -->
            
            <!-- Social links -->
            <div class="site-footer-social social-links social-links-text">
                <a href="http://vk.com/lift2future" class="social-link social-link-vk">вКонтакте</a>
                <a href="https://www.facebook.com/pages/Лифт-в-будущее-поддержка-молодых-талантов/226756564102174" class="social-link social-link-facebook">Facebook</a>
                <a href="https://twitter.com/lift2future" class="social-link social-link-twitter">Twitter</a>
                <a href="mailto:konkurs.sp@lifttothefuture.ru" class="social-link social-link-email">Электропочта</a>
            </div>
            <!-- /Social links -->
        </div>
    </div>
</div>