<?
extract([
    'classes' => ''
], EXTR_SKIP);
?>

<div class="promo-block <?= $classes ?>">
    <h2 class="promo-block-main-heading">Этот Лифт идёт в Будущее. Ты учишься в школе или институте,<br>но уже готов начать карьеру? Присоединяйся!</h2>
    
    <!-- Switcher -->
    <ul class="promo-block-switcher row" id="promo-block-switcher">
        <li class="col-3">
            <a data-slide-index="0">Школьникам</a>
        </li>
        <li class="col-3">
            <a data-slide-index="1">Студентам</a>
        </li>
        <li class="col-3">
            <a data-slide-index="2">Родителям</a>
        </li>
        <li class="col-3">
            <a data-slide-index="3">Партнёрам</a>
        </li>
    </ul>
    <!-- /Switcher -->
    
    <!-- Content -->
    <div class="promo-block-content">
        <!-- Schoolkid -->
        <div class="promo-block-content-tab">
            <img class="promo-block-content-image" src="/img/promo-schoolgirl.jpg" alt="" width="191" height="426">
            
            <div class="promo-block-content-body">
                <p class="promo-block-text">Если ты решил связать свою жизнь, учебу и карьеру с наукой, но еще не смог определиться, куда именно направить свои стремления, проект ЛИФТ В БУДУЩЕЕ – это то, что тебе нужно. Ведь поступление в вуз – это не только экзамены. Творческие работы, стажировки, летние школы, научные лекции и статьи, все это сможет заложить необходимую базу знаний и навыков, которые помогут тебе найти свое место в науке!</p>
                <p style="font-size: 24px; margin-top: 35px; margin-bottom: 20px;">Присоединяйся!</p>
                <ul>
                    <li>Расскажи о своих идеях</li>
                    <li>Делай интересные проекты</li>
                    <li>Создай уникальное CV</li>
                    <li>Найди новых друзей</li>
                </ul>
            </div>
        </div>
        <!-- /Schoolkid -->
        
        <!-- Student -->
        <div class="promo-block-content-tab">
            <img class="promo-block-content-image" src="/img/promo-student.jpg" alt="" width="180" height="500">
            
            <div class="promo-block-content-body">
                <p class="promo-block-text">Если ты решил связать свою жизнь, учебу и карьеру с наукой, но еще не смог определиться, куда именно направить свои стремления, проект ЛИФТ В БУДУЩЕЕ – это то, что тебе нужно. Ведь поступление в вуз – это не только экзамены. Творческие работы, стажировки, летние школы, научные лекции и статьи, все это сможет заложить необходимую базу знаний и навыков, которые помогут тебе найти свое место в науке!</p>
                <p style="font-size: 24px; margin-top: 35px; margin-bottom: 20px;">Присоединяйся!</p>
                <ul>
                    <li>Расскажи о своих идеях</li>
                    <li>Делай интересные проекты</li>
                    <li>Создай уникальное CV</li>
                    <li>Найди новых друзей</li>
                </ul>
            </div>
        </div>
        <!-- /Student -->
        
        <!-- Parents -->
        <div class="promo-block-content-tab">
            <img class="promo-block-content-image" src="/img/promo-parent.jpg" alt="" width="150" height="465">
            
            <div class="promo-block-content-body">
                <p class="promo-block-text">Выбор профессии, определение карьерной траектории – сложный процесс в котором не последнюю роль играет семья будущего специалиста. Программа «Лифт в будущее» поможет сориентироваться в многочисленных возможностях и сформировать прочный фундамент для дальнейшего развития. </p>
                
                <h3>Формирование портфолио:</h3>
                <ul>
                    <li>Всероссийский конкурс школьных проектов «Система приоритетов»</li>
                    <li>Научно-образовательные школы «Лифт в будущее»</li>
                    <li>Международная научная конференция школьников «Лифт в будущее»</li>
                </ul>
                
                <h3>Вклад в карьерное развитие:</h3>
                <ul>
                    <li>Конкурс студенческих проектов Intellect2all</li>
                    <li>Стажировки</li>
                </ul>
            </div>
        </div>
        <!-- /Parents -->
        
        <!-- Partners -->
        <div class="promo-block-content-tab">
            <img class="promo-block-content-image" src="/img/promo-partner.jpg" alt="" width="143" height="491">
            
            <div class="promo-block-content-body">
                <p class="promo-block-text">Залогом успеха и качества программы «Лифт в будущее» является активная партнерская сеть. Уже сейчас мы взаимовыгодно сотрудничаем с большим количеством успешных организаций в сфере бизнеса, гражданских инициатив и образования. Мы создаем условия, для того что бы все могли внести свой ценный вклад в развитие страны. Инвестиции в детей – инвестиции в будущее. </p>
                
                <h3>Наши партнёры</h3>
                <div>
                    <img src="/img/partners/sistema.png" height="30" alt="" style="vertical-align: middle;">
                    <img src="/img/partners/asi.png" height="40" alt="" style="vertical-align: middle; margin-left: 30px">
                </div>
                
                <h3>Экспертная и финансовая поддержка:</h3>
                <ul>
                    <li>Научно-образовательные школы «Лифт в будущее»</li>
                    <li>Международная научная конференция школьников «Лифт в будущее»</li>
                    <li>Конкурс студенческих проектов Intellect2all</li>
                </ul>
                
                <h3>Образовательным партнёрам:</h3>
                <ul>
                    <li>Проект «Вузы будущего»</li>
                    <li>Типовой Договор о сотрудничестве с Высшими учебными заведениями</li>
                    <li>Новые возможности для ваших студентов</li>
                </ul>
            </div>
        </div>
        <!-- /Partners -->
    </div>
    <!-- /Content -->
</div>