Оригинал: 200x390 <br>
<img src="/upload/6731628832.jpg"><hr>

<hr><hr><hr><hr>

<h1>zoom1</h1>

Обрезка 100x200<br>
<img src="/image/zoom1/100x200/upload/6731628832.jpg"><hr>

Обрезка 200x100<br>
<img src="/image/zoom1/200x100/upload/6731628832.jpg"><hr>

Обрезка 200x0<br>
<img src="/image/zoom1/200x0/upload/6731628832.jpg"><hr>

Обрезка 0x200<br>
<img src="/image/zoom1/0x200/upload/6731628832.jpg"><hr>

<hr><hr><hr><hr>


<h1>zoom2</h1>



Обрезка 100x200<br>
<img src="/image/zoom2/100x200/upload/6731628832.jpg"><hr>

Обрезка 200x100<br>
<img src="/image/zoom2/200x100/upload/6731628832.jpg"><hr>

Обрезка 200x0<br>
<img src="/image/zoom2/200x0/upload/6731628832.jpg"><hr>

Обрезка 0x200<br>
<img src="/image/zoom2/0x200/upload/6731628832.jpg"><hr>

<hr><hr><hr><hr>


<h1>zoom3</h1>



Обрезка 100x200<br>
<img src="/image/zoom3/100x200/upload/6731628832.jpg"><hr>

Обрезка 200x100<br>
<img src="/image/zoom3/200x100/upload/6731628832.jpg"><hr>

Обрезка 200x0<br>
<img src="/image/zoom3/200x0/upload/6731628832.jpg"><hr>

Обрезка 0x200<br>
<img src="/image/zoom3/0x200/upload/6731628832.jpg"><hr>

<hr><hr><hr><hr>




Оригинал: 600x337 <br>
<img src="/upload/BtgXcKyIMAABUPk.jpg"><hr>
<hr><hr><hr><hr>

<h1>zoom1</h1>

Обрезка 100x200<br>
<img src="/image/zoom1/100x200/upload/BtgXcKyIMAABUPk.jpg"><hr>

Обрезка 200x100<br>
<img src="/image/zoom1/200x100/upload/BtgXcKyIMAABUPk.jpg"><hr>

Обрезка 200x0<br>
<img src="/image/zoom1/200x0/upload/BtgXcKyIMAABUPk.jpg"><hr>

Обрезка 0x200<br>
<img src="/image/zoom1/0x200/upload/BtgXcKyIMAABUPk.jpg"><hr>

<hr><hr><hr><hr>


<h1>zoom2</h1>


Обрезка 100x200<br>
<img src="/image/zoom2/100x200/upload/BtgXcKyIMAABUPk.jpg"><hr>

Обрезка 200x100<br>
<img src="/image/zoom2/200x100/upload/BtgXcKyIMAABUPk.jpg"><hr>

Обрезка 200x0<br>
<img src="/image/zoom2/200x0/upload/BtgXcKyIMAABUPk.jpg"><hr>

Обрезка 0x200<br>
<img src="/image/zoom2/0x200/upload/BtgXcKyIMAABUPk.jpg"><hr>

<hr><hr><hr><hr>

<h1>zoom3</h1>


Обрезка 100x200<br>
<img src="/image/zoom3/100x200/upload/BtgXcKyIMAABUPk.jpg"><hr>

Обрезка 200x100<br>
<img src="/image/zoom3/200x100/upload/BtgXcKyIMAABUPk.jpg"><hr>

Обрезка 200x0<br>
<img src="/image/zoom3/200x0/upload/BtgXcKyIMAABUPk.jpg"><hr>

Обрезка 0x200<br>
<img src="/image/zoom3/0x200/upload/BtgXcKyIMAABUPk.jpg"><hr>

<hr><hr><hr><hr>

