<div class="page-header project-header"  <?= !empty($project['background']) ? 'style="background-image: url(\'/upload/' . $project['background'] . '\')"' : '' ?>>
    <div class="container">
        <div class="page-header-inner">
            <div class="page-header-top">
                <div class="page-header-cell">
                    <h1 class="page-header-title"><?= $project['title'] ?></h1>
                </div>
            </div>
        </div>
    </div>
</div>